# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_H-NE6Hzy0N38OKmmDZZoVr_VZ20amoM

# **Language Translator**


## Note: You must obtain the API keys and enpoints to complete the lab.
"""

#you will need the following library 
!pip install ibm_watson wget

"""*   First we import SpeechToTextV1 from ibm_watson."""

import json

from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

"""* The service endpoint is based on the location of the service instance, we store the information in the variable URL. To find out which URL to use, view the service credentials."""

url_lt = "https://api.eu-gb.language-translator.watson.cloud.ibm.com/instances/a281e485-e2f4-4a42-acec-bce44e6bb13f"

"""*  You require an API key, and you can obtain the key on the IBM Cloud Dashboard ."""

apikey_lt = "tOwYi4E7fLwQTdYoYrPwcOjGE7DOKXDTzWobgIh6MpDn"

from ibm_watson import SpeechToTextV1

"""*   import LanguageTranslatorV3 from ibm_watson."""

from ibm_watson import LanguageTranslatorV3

"""*   API requests require a version parameter that takes a date in the format version=YYYY-MM-DD. This lab describes the current version of Language Translator, 2018-05-01"""

version_lt='2018-05-01'

"""*   we create a Language Translator object language_translator:"""

authenticator = IAMAuthenticator(apikey_lt)
language_translator = LanguageTranslatorV3(version=version_lt,authenticator=authenticator)
language_translator.set_service_url(url_lt)
language_translator

"""*   We can get a Lists the languages that the service can identify. The method Returns the language code."""

from pandas.io.json import json_normalize

json_normalize(language_translator.list_identifiable_languages().get_result(), "languages")

!wget -O Example1.txt https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/labs/example1.txt

file1 = "Example1.txt"
filer = open(file1,"r")
filew = filer.read()
print(filew)

"""*  this will translate the text. The parameter text is the text. Model_id is the type of model we would like to use use we use list the the langwich . In this case, we set it to 'en-es' or English to Spanish. We get a Detailed Response object translation_response"""

translation_response = language_translator.translate(
    text=filew, model_id='en-es')
translation_response

"""*  The result is a dictionary."""

translation=translation_response.get_result()
translation

"""*   We can obtain the actual translation as a string as follows:"""

spanish_translation =translation['translations'][0]['translation']
spanish_translation

"""*   We can translate back to English"""

translation_new = language_translator.translate(text=spanish_translation ,model_id='es-en').get_result()

"""*  We can obtain the actual translation as a string as follows:"""

translation_eng=translation_new['translations'][0]['translation']
translation_eng

"""*   We can convert it to french as well:"""

French_translation=language_translator.translate(
    text=filew , model_id='en-fr').get_result()

French_translation['translations'][0]['translation']

"""*  Converting into Bengali from english"""

Bengali_translation=language_translator.translate(
    text=filew , model_id='en-bn').get_result()

Bengali_translation['translations'][0]['translation']

"""*  Converting into Urdu from english"""

Urdu_translation=language_translator.translate(
    text=filew , model_id='en-ur').get_result()

Urdu_translation['translations'][0]['translation']

"""*  Converting into Simplified Chinese from english"""

Simplified_Chinese_translation=language_translator.translate(
    text=filew , model_id='en-zh').get_result()

Simplified_Chinese_translation['translations'][0]['translation']

"""*  Converting into German from english"""

German_translation=language_translator.translate(
    text=filew , model_id='en-de').get_result()

German_translation['translations'][0]['translation']

"""*  Converting into Gujarati from english"""

Gujarati_translation=language_translator.translate(
    text=filew , model_id='en-gu').get_result()

Gujarati_translation['translations'][0]['translation']

"""*  Converting into Hindi from english"""

Hindi_translation=language_translator.translate(
    text=filew , model_id='en-hi').get_result()

Hindi_translation['translations'][0]['translation']

"""# New Section"""